import {useState} from 'react'
import {api} from '../lib/api'
import {navigate} from '../lib/router'
import {Notice} from '../components/Notice'

type Session={name:string;email:string;expiresAt:string}
export function AccountPage({session}:{session:Session}){
 const [name,setName]=useState(session.name),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[deletePhrase,setDeletePhrase]=useState(''),[deleting,setDeleting]=useState(false),[deleteOpen,setDeleteOpen]=useState(false)
 async function saveName(event:React.FormEvent){event.preventDefault();setSaving(true);try{await api('/api/account/profile',{method:'PUT',body:JSON.stringify({name})});setNotice('이름을 저장했습니다.')}catch(error){setNotice((error as Error).message)}finally{setSaving(false)}}
 async function changePassword(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(form.get('password')!==form.get('confirm'))return setNotice('비밀번호 확인이 일치하지 않습니다.');try{await api('/api/account/password',{method:'PUT',body:JSON.stringify({currentPassword:form.get('currentPassword'),password:form.get('password')})});setNotice('비밀번호를 변경했습니다. 다시 로그인해 주세요.');navigate('/login',true)}catch(error){setNotice((error as Error).message)}}
 async function deleteAccount(event:React.FormEvent){event.preventDefault();if(deletePhrase!=='탈퇴합니다')return setNotice('확인 문구로 “탈퇴합니다”를 정확히 입력해 주세요.');setDeleting(true);try{await api('/api/account',{method:'DELETE',body:JSON.stringify({phrase:deletePhrase})});navigate('/login',true)}catch(error){setNotice((error as Error).message);setDeleting(false)}}
 return <section className="account-page"><header className="page-actions account-page-actions"><div><span className="eyebrow">ACCOUNT SETTINGS</span><h2>계정 설정</h2></div><button type="button" className="danger-button account-delete-trigger" onClick={()=>{setDeletePhrase('');setDeleteOpen(true)}}>회원 탈퇴</button></header><div className="account-grid"><div className="account-left"><section className="panel account-section"><h3>이름</h3><p>서비스 안에서 표시할 이름을 바꿉니다.</p><form onSubmit={saveName}><label>이름<input value={name} onChange={event=>setName(event.target.value)} maxLength={40} required/></label><button className="primary" disabled={saving}>{saving?'저장 중…':'이름 저장'}</button></form></section><section className="panel account-section account-data"><h3>내 데이터</h3><p>내 기록 전체를 JSON 파일 하나로 내려받을 수 있습니다.</p><a className="primary account-export" href="/api/export">전체 데이터 내보내기</a></section></div><section className="panel account-section"><h3>비밀번호</h3><p>변경을 완료하면 모든 로그인 세션이 종료됩니다.</p><form onSubmit={changePassword}><label>현재 비밀번호<input name="currentPassword" type="password" required/></label><label>새 비밀번호<input name="password" type="password" minLength={8} required/><small>8자 이상, 영문과 숫자를 함께 입력해 주세요.</small></label><label>새 비밀번호 확인<input name="confirm" type="password" minLength={8} required/></label><button className="primary">비밀번호 변경</button></form></section></div>{deleteOpen&&<div className="dialog-backdrop account-delete-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setDeleteOpen(false)}}><section className="account-delete-modal" role="dialog" aria-modal="true" aria-labelledby="account-delete-title"><header><div><span className="eyebrow">DANGER ZONE</span><h2 id="account-delete-title">회원 탈퇴</h2></div><button type="button" className="account-modal-close" onClick={()=>setDeleteOpen(false)} aria-label="회원 탈퇴 모달 닫기">×</button></header><div className="account-delete-content"><p>계획, 할 일, 태그, 실행 기록, 회고와 로그인 정보를 모두 영구 삭제합니다.</p><form onSubmit={deleteAccount}><label>확인 문구<input value={deletePhrase} onChange={event=>setDeletePhrase(event.target.value)} placeholder="탈퇴합니다" autoComplete="off" required/></label><button className="danger-button" disabled={deleting||deletePhrase!=='탈퇴합니다'}>{deleting?'삭제 중…':'계정과 모든 자료 삭제'}</button></form></div></section></div>}<Notice message={notice} onClose={()=>setNotice('')}/></section>
}
