import {useCallback,useEffect,useMemo,useState} from 'react'
import type {FormEvent} from 'react'
import {api} from '../lib/api'
import type {Plan,Task} from '../lib/types'
import {minutes,priorityLabel,tagList,today} from '../lib/types'
import {navigate} from '../lib/router'
import {Notice} from '../components/Notice'
import {BackButton} from '../components/BackButton'
import {PriorityPicker} from '../components/PriorityPicker'
import {TagPicker} from '../components/TagPicker'

const MAX_TASKS=20

export function PlanDetailPage({plan,onChanged}:{plan:Plan;onChanged:()=>Promise<void>}){
 const [tasks,setTasks]=useState<Task[]|null>(null),[editingPlan,setEditingPlan]=useState(false),[editingTaskId,setEditingTaskId]=useState(''),[addOpen,setAddOpen]=useState(false),[taskQuery,setTaskQuery]=useState(''),[taskStatus,setTaskStatus]=useState(''),[taskTag,setTaskTag]=useState(''),[notice,setNotice]=useState('')
 const load=useCallback(async()=>setTasks(await api<Task[]>(`/api/tasks?planId=${encodeURIComponent(plan.id)}&sort=due`)),[plan.id])
 // Load the selected plan's server-backed tasks when the page opens.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load])
 async function updatePlan(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);try{await api(`/api/plans/${plan.id}`,{method:'PUT',body:JSON.stringify({title:f.get('title'),priority:f.get('priority'),successCriteria:f.get('successCriteria')})});setEditingPlan(false);setNotice('계획을 수정하고 이전 값을 이력에 남겼습니다.');await onChanged()}catch(error){setNotice((error as Error).message)}}
 async function removePlan(){if(!confirm(`“${plan.title}” 계획을 삭제할까요?\n실행 기록은 DB에 보존됩니다.`))return;try{await api(`/api/plans/${plan.id}`,{method:'DELETE'});await onChanged();navigate('/plans')}catch(error){setNotice((error as Error).message)}}
 async function addTask(event:FormEvent<HTMLFormElement>){event.preventDefault();if((tasks?.length??0)>=MAX_TASKS){setAddOpen(false);setNotice(`계획마다 할 일은 최대 ${MAX_TASKS}개까지 추가할 수 있습니다.`);return}const form=event.currentTarget,f=new FormData(form);try{await api('/api/tasks',{method:'POST',body:JSON.stringify({planId:plan.id,title:f.get('title'),dueDate:f.get('dueDate'),priority:f.get('priority'),estimatedMinutes:Number(f.get('estimatedMinutes')),tags:tagList(f.get('tags'))})});form.reset();setAddOpen(false);setNotice('할 일을 추가했습니다.');await Promise.all([load(),onChanged()])}catch(error){setNotice((error as Error).message)}}
 async function updateTask(event:FormEvent<HTMLFormElement>,task:Task){event.preventDefault();const f=new FormData(event.currentTarget);try{await api(`/api/tasks/${task.id}`,{method:'PUT',body:JSON.stringify({planId:plan.id,title:f.get('title'),dueDate:f.get('dueDate'),priority:f.get('priority'),estimatedMinutes:Number(f.get('estimatedMinutes')),tags:tagList(f.get('tags'))})});setEditingTaskId('');setNotice('할 일을 수정했습니다.');await load()}catch(error){setNotice((error as Error).message)}}
 async function removeTask(task:Task){if(!confirm(`“${task.title}”을 삭제할까요?`))return;try{await api(`/api/tasks/${task.id}`,{method:'DELETE'});await Promise.all([load(),onChanged()])}catch(error){setNotice((error as Error).message)}}
 const taskRows=useMemo(()=>tasks??[],[tasks])
 const atTaskLimit=taskRows.length>=MAX_TASKS
 const taskTags=useMemo(()=>Array.from(new Set(taskRows.flatMap(task=>task.tags))).sort((a,b)=>a.localeCompare(b,'ko-KR')),[taskRows])
 const visibleTasks=useMemo(()=>taskRows.filter(task=>(!taskQuery||task.title.toLocaleLowerCase('ko-KR').includes(taskQuery.toLocaleLowerCase('ko-KR')))&&(!taskStatus||task.status===taskStatus)&&(!taskTag||task.tags.includes(taskTag))),[taskRows,taskQuery,taskStatus,taskTag])
 return <><section className="panel plan-detail"><BackButton to="/plans">계획 목록</BackButton><div className="list-head"><div><div className="eyebrow">계획 상세</div><h2>{plan.title}</h2></div><div className="button-row"><button className="edit-task-button" onClick={()=>setEditingPlan(value=>!value)}>{editingPlan?'수정 취소':'계획 수정'}</button><button className="danger-button" onClick={removePlan}>계획 삭제</button></div></div><div className="detail-grid"><div><small>우선순위</small><b>{priorityLabel[plan.priority]}</b></div><div><small>할 일 예상 합계</small><b>{minutes(plan.task_estimated_minutes)}</b></div><div><small>진행 상황</small><b>{plan.completed_count}/{plan.task_count} 완료</b></div><div className="detail-wide"><small>성공 기준</small><b>{plan.success_criteria}</b></div></div>
 {editingPlan&&<form className="edit-form" onSubmit={updatePlan}><label>계획 이름<input name="title" defaultValue={plan.title} required/></label><PriorityPicker name="priority" defaultValue={plan.priority}/><label>성공 기준<textarea name="successCriteria" defaultValue={plan.success_criteria} required/></label><button className="primary edit-submit">계획 수정 저장</button></form>}
 <div className="plan-flow-actions"><div><b>계획 실행과 돌아보기</b><span>할 일별 실행 기록을 남긴 뒤 계획 전체를 돌아봅니다.</span></div><button className="review-button" onClick={()=>navigate(`/plans/${plan.id}/review`)}>이 계획 돌아보기 →</button></div>
 <section className="task-manager"><div className="task-manager-head"><div><span className="eyebrow">TASKS</span><h3>소속 할 일 <small>{tasks===null?'불러오는 중':`${taskRows.length}개 · 최대 ${MAX_TASKS}개`}</small></h3></div><button className="primary create-button" disabled={tasks===null||atTaskLimit} title={atTaskLimit?`계획마다 최대 ${MAX_TASKS}개까지 추가할 수 있습니다.`:'할 일 추가'} onClick={()=>setAddOpen(value=>!value)}>{atTaskLimit?`최대 ${MAX_TASKS}개`:addOpen?'추가 취소':'+ 할 일 추가'}</button></div>
 {addOpen&&<form className="quick-task" onSubmit={addTask}><label>할 일<input name="title" required/></label><div className="row"><label>마감일<input name="dueDate" type="date" defaultValue={today} required/></label><label>예상 시간(분)<input name="estimatedMinutes" type="number" min="0" defaultValue="30" required/></label></div><div className="row"><PriorityPicker name="priority"/><TagPicker name="tags"/></div><button className="primary create-button">할 일 저장</button></form>}
 <div className="task-list-toolbar"><input aria-label="할 일 검색" placeholder="할 일 검색" value={taskQuery} onChange={event=>setTaskQuery(event.target.value)}/><select aria-label="상태 필터" value={taskStatus} onChange={event=>setTaskStatus(event.target.value)}><option value="">모든 상태</option><option value="active">진행 중</option><option value="completed">완료</option></select><select aria-label="태그 필터" value={taskTag} onChange={event=>setTaskTag(event.target.value)}><option value="">모든 태그</option>{taskTags.map(tag=><option value={tag} key={tag}>{tag}</option>)}</select></div>
 <div className="plan-task-list">{tasks===null?<div className="empty loading-state">할 일을 불러오는 중입니다.</div>:<>{visibleTasks.map(task=>editingTaskId===task.id?<form className="task-edit" key={task.id} onSubmit={event=>updateTask(event,task)}><label>할 일<input name="title" defaultValue={task.title} required/></label><div className="row"><label>마감일<input name="dueDate" type="date" defaultValue={task.due_date} required/></label><label>예상 시간(분)<input name="estimatedMinutes" type="number" min="0" defaultValue={task.estimated_minutes} required/></label></div><div className="row"><PriorityPicker name="priority" defaultValue={task.priority}/><TagPicker name="tags" defaultValue={task.tags}/></div><div className="button-row"><button className="primary edit-submit">수정 저장</button><button type="button" className="secondary" onClick={()=>setEditingTaskId('')}>취소</button></div></form>:<article className="manage-task" key={task.id}><div className="manage-task-copy"><span className={`badge ${task.priority}`}>{priorityLabel[task.priority]}</span><h3>{task.title}</h3><p>마감 {task.due_date} · 예상 {minutes(task.estimated_minutes)} {task.tags.map(tag=><span className="tag" key={tag}>#{tag}</span>)}</p></div><div className="button-row task-actions"><button className="action-button" onClick={()=>navigate(`/plans/${plan.id}/tasks/${task.id}/action`)}>실행 기록</button><button className="edit-task-button" onClick={()=>setEditingTaskId(task.id)}>수정</button><button className="delete-task-button" disabled={taskRows.length<=1} title={taskRows.length<=1?'계획에는 할 일이 1개 이상 필요합니다.':'할 일 삭제'} onClick={()=>removeTask(task)}>삭제</button></div></article>)}{!visibleTasks.length&&<div className="empty">{taskRows.length?'조건에 맞는 할 일이 없습니다.':'이 계획에 등록된 할 일이 없습니다.'}</div>}</>}</div></section></section><Notice message={notice} onClose={()=>setNotice('')}/></>
}
