import { Hono } from 'hono'
import { z } from 'zod'
import {code,digest,password,sign,token,verificationTtlMinutes,sessionTtlSeconds,sendVerificationEmail,same,readCookie} from './auth.js'

type Bindings = { DB:D1Database; SMTP_HOST?:string; SMTP_PORT?:string; SMTP_USER?:string; SMTP_PASS?:string; MAIL_FROM?:string; AUTH_SECRET?:string }
const app = new Hono<{ Bindings: Bindings; Variables:{user:SessionUser} }>()
const MAX_TASKS_PER_PLAN = 20
const priority = z.enum(['low', 'medium', 'high'])
const calendarDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/)
const planFields = { title:z.string().trim().min(1).max(120), priority, successCriteria:z.string().trim().min(1).max(1000) }
const taskFields = { title:z.string().trim().min(1).max(200), dueDate:calendarDate, priority, estimatedMinutes:z.number().int().min(0), tags:z.array(z.string().trim().min(1).max(30)).max(10).default([]) }
const planSchema = z.object(planFields)
const createPlanSchema = z.object({...planFields,tasks:z.array(z.object(taskFields)).min(1,'할 일을 1개 이상 추가해 주세요.').max(MAX_TASKS_PER_PLAN,`할 일은 최대 ${MAX_TASKS_PER_PLAN}개까지 추가할 수 있습니다.`)})
const taskSchema = z.object({ planId:z.string(), ...taskFields })
const actionSchema = z.object({ taskId:z.string(), workedOn:calendarDate.optional(), startedAt:z.string().datetime({offset:true}).optional(), actualMinutes:z.number().int().min(0), note:z.string().trim().max(1000).default('') })
 .refine(v=>Boolean(v.workedOn||v.startedAt),{message:'작업일을 입력해 주세요.',path:['workedOn']})
 .transform(v=>({taskId:v.taskId,workedOn:v.workedOn??seoulDate(new Date(v.startedAt!)),actualMinutes:v.actualMinutes,note:v.note}))
const statusSchema = z.object({ completed:z.boolean(), expectedVersion:z.number().int().min(0), idempotencyKey:z.string().min(8).max(200) })
const reviewSchema = z.object({ planId:z.string(), improvementText:z.string().trim().min(1).max(500) })
const emailSchema=z.object({email:z.string().trim().email('올바른 이메일 주소를 입력해 주세요.').max(254,'이메일 주소가 너무 깁니다.').transform(v=>v.toLowerCase())})
const loginSchema=emailSchema.extend({password:z.string().min(8,'비밀번호를 8자 이상 입력해 주세요.').max(128,'비밀번호가 너무 깁니다.')})
const now=()=>new Date().toISOString()
const uid=(prefix:string)=>`${prefix}_${crypto.randomUUID()}`
function seoulDate(value:Date){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(value)}
type SessionUser={id:string;name:string|null;email:string;expires_at:string;password_hash:string;password_salt:string}
async function sessionUser(request:Request,db:D1Database){const raw=readCookie(request,'pva_session');if(!raw)return null;return db.prepare('SELECT u.id,u.name,u.email,u.password_hash,u.password_salt,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>?').bind(await digest(raw),now()).first<SessionUser>()}


async function input<T>(request:Request,schema:z.ZodType<T>){ return schema.parse(await request.json()) }
function taskQuery(where:string){return `SELECT t.*,p.title plan_title,COALESCE(GROUP_CONCAT(DISTINCT g.name),'') tag_names,COALESCE((SELECT SUM(a.actual_minutes) FROM actions a WHERE a.task_id=t.id),0) actual_minutes FROM tasks t JOIN plans p ON p.id=t.plan_id LEFT JOIN task_tags tt ON tt.task_id=t.id LEFT JOIN tags g ON g.id=tt.tag_id AND g.user_id=p.user_id WHERE ${where} GROUP BY t.id`}
function withTags(row:Record<string,unknown>){return {...row,tags:typeof row.tag_names==='string'&&row.tag_names?row.tag_names.split(','):[]}}
async function planTaskCount(db:D1Database,planId:string,userId:string){return db.prepare('SELECT p.id,COUNT(t.id) task_count FROM plans p LEFT JOIN tasks t ON t.plan_id=p.id AND t.deleted_at IS NULL WHERE p.id=? AND p.user_id=? AND p.deleted_at IS NULL GROUP BY p.id').bind(planId,userId).first<{id:string;task_count:number}>()}
function tagParts(value:string){
 let name=value.normalize('NFKC').trim().replace(/\s+/g,' ').replace(/^#+\s*/,'')
 const wrappers:Record<string,string>={'[':']','(':')','{':'}','"':'"',"'":"'"}
 const closing=wrappers[name[0]]
 if(closing&&name.endsWith(closing))name=name.slice(1,-1).trim()
 const normalizedName=name.toLocaleLowerCase('ko-KR').replace(/\s+/g,'')
 const ignored=`._-[](){}"'`
 const searchKey=[...normalizedName].filter(character=>!ignored.includes(character)).join('')
 return{name,normalizedName,searchKey}
}

app.use('/api/*',async(c,next)=>{await next();c.header('Cache-Control','no-store');c.header('X-Content-Type-Options','nosniff')})
app.use('/api/*',async(c,next)=>{const protectedPath=['/api/plans','/api/tasks','/api/tags','/api/actions','/api/reviews','/api/summary','/api/evidence','/api/export','/api/account'].some(prefix=>c.req.path===prefix||c.req.path.startsWith(`${prefix}/`));if(!protectedPath)return next();const user=await sessionUser(c.req.raw,c.env.DB);if(!user)return c.json({error:'로그인이 필요합니다.'},401);c.set('user',user);return next()})
app.onError((error,c)=>error instanceof z.ZodError?c.json({error:'입력값을 확인해 주세요.',details:error.issues.map(issue=>({path:issue.path}))},400):(console.error(error),c.json({error:'요청을 처리하지 못했습니다.'},500)))
app.get('/api/health',c=>c.json({ok:true,database:'D1',timezone:'Asia/Seoul'}))
app.post('/api/auth/signup',async c=>{const v=await input(c.req.raw,emailSchema);if(!c.env.AUTH_SECRET)return c.json({error:'인증 설정이 없습니다.'},503);const exists=await c.env.DB.prepare('SELECT id FROM users WHERE email=?').bind(v.email).first();if(exists)return c.json({error:'이미 가입된 이메일입니다.'},409);const flow=uid('signup'),raw=token(),value=code(),ts=now();await c.env.DB.prepare("UPDATE email_verifications SET status='expired',updated_at=? WHERE email=? AND purpose='signup' AND status IN ('pending','verified')").bind(ts,v.email).run();await c.env.DB.prepare("INSERT INTO email_verifications(id,email,code_hash,flow_token_hash,status,expires_at,created_at,updated_at,purpose) VALUES(?,?,?,?,?,?,?,?, 'signup')").bind(flow,v.email,await sign(value,c.env.AUTH_SECRET),await digest(raw),'pending',new Date(Date.now()+verificationTtlMinutes*60000).toISOString(),ts,ts).run();await sendVerificationEmail(c.env,v.email,value);return c.json({flowId:flow,flowToken:raw},201)})
app.post('/api/auth/verify-email',async c=>{const v=await input(c.req.raw,z.object({email:z.string().trim().email('올바른 이메일 주소를 입력해 주세요.').transform(x=>x.toLowerCase()),code:z.string().regex(/^\d{6}$/,'인증번호 6자리를 입력해 주세요.'),flowId:z.string(),flowToken:z.string()}));if(!c.env.AUTH_SECRET)return c.json({error:'인증 설정이 없습니다.'},503);const flow=await c.env.DB.prepare("SELECT id,code_hash FROM email_verifications WHERE id=? AND email=? AND purpose='signup' AND flow_token_hash=? AND status='pending' AND expires_at>?").bind(v.flowId,v.email,await digest(v.flowToken),now()).first<{id:string;code_hash:string}>();if(!flow||!same(flow.code_hash,await sign(v.code,c.env.AUTH_SECRET)))return c.json({error:'인증번호가 올바르지 않거나 만료되었습니다.'},400);await c.env.DB.prepare("UPDATE email_verifications SET status='verified',updated_at=? WHERE id=?").bind(now(),flow.id).run();return c.json({ok:true})})
app.post('/api/auth/complete-signup',async c=>{const v=await input(c.req.raw,z.object({flowId:z.string(),flowToken:z.string(),name:z.string().trim().min(1).max(40),password:z.string().min(8).max(128).refine(value=>/[A-Za-z]/.test(value)&&/[0-9]/.test(value),'비밀번호는 영문과 숫자를 함께 입력해 주세요.')}));const flow=await c.env.DB.prepare("SELECT email FROM email_verifications WHERE id=? AND purpose='signup' AND flow_token_hash=? AND status='verified' AND expires_at>?").bind(v.flowId,await digest(v.flowToken),now()).first<{email:string}>();if(!flow)return c.json({error:'가입 인증이 만료되었거나 현재 창의 요청이 아닙니다.'},403);const hash=await password(v.password),id=uid('user'),ts=now(),raw=token();await c.env.DB.batch([c.env.DB.prepare('INSERT INTO users(id,email,password_hash,password_salt,name,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id,flow.email,hash.hash,hash.salt,v.name,ts,ts),c.env.DB.prepare("UPDATE email_verifications SET status='completed',user_id=?,updated_at=? WHERE id=?").bind(id,ts,v.flowId),c.env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)').bind(uid('session'),id,await digest(raw),new Date(Date.now()+sessionTtlSeconds*1000).toISOString(),ts)]);c.header('Set-Cookie',`pva_session=${raw}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${sessionTtlSeconds}`);return c.json({ok:true})})
app.post('/api/auth/login',async c=>{const v=await input(c.req.raw,loginSchema),user=await c.env.DB.prepare('SELECT id,password_hash,password_salt FROM users WHERE email=?').bind(v.email).first<{id:string;password_hash:string;password_salt:string}>();if(!user||!same((await password(v.password,user.password_salt)).hash,user.password_hash))return c.json({error:'이메일 또는 비밀번호가 올바르지 않습니다.'},401);const raw=token(),ts=now();await c.env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)').bind(uid('session'),user.id,await digest(raw),new Date(Date.now()+sessionTtlSeconds*1000).toISOString(),ts).run();c.header('Set-Cookie',`pva_session=${raw}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${sessionTtlSeconds}`);return c.json({ok:true})})
app.post('/api/auth/logout',async c=>{const raw=c.req.header('Cookie')?.match(/(?:^|;\s*)pva_session=([^;]+)/)?.[1];if(raw)await c.env.DB.prepare('UPDATE sessions SET revoked_at=? WHERE token_hash=?').bind(now(),await digest(raw)).run();c.header('Set-Cookie','pva_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return c.json({ok:true})})
app.get('/api/auth/me',async c=>{const user=await sessionUser(c.req.raw,c.env.DB);return user?c.json({name:user.name??user.email,email:user.email,expiresAt:user.expires_at}):c.json({error:'로그인이 필요합니다.'},401)})
app.post('/api/auth/session/refresh',async c=>{const raw=readCookie(c.req.raw,'pva_session');if(!raw)return c.json({error:'로그인이 필요합니다.'},401);const expiresAt=new Date(Date.now()+sessionTtlSeconds*1000).toISOString(),result=await c.env.DB.prepare('UPDATE sessions SET expires_at=? WHERE token_hash=? AND revoked_at IS NULL AND expires_at>?').bind(expiresAt,await digest(raw),now()).run();return result.meta.changes?c.json({expiresAt}):c.json({error:'로그인이 필요합니다.'},401)})
app.put('/api/account/profile',async c=>{const user=await sessionUser(c.req.raw,c.env.DB);if(!user)return c.json({error:'로그인이 필요합니다.'},401);const v=await input(c.req.raw,z.object({name:z.string().trim().min(1,'이름을 입력해 주세요.').max(40,'이름은 40자까지 입력할 수 있습니다.')}));await c.env.DB.prepare('UPDATE users SET name=?,updated_at=? WHERE id=?').bind(v.name,now(),user.id).run();return c.json({name:v.name})})
app.put('/api/account/password',async c=>{const user=await sessionUser(c.req.raw,c.env.DB);if(!user)return c.json({error:'로그인이 필요합니다.'},401);const v=await input(c.req.raw,z.object({currentPassword:z.string().min(1,'현재 비밀번호를 입력해 주세요.'),password:z.string().min(8,'비밀번호를 8자 이상 입력해 주세요.').max(128,'비밀번호가 너무 깁니다.').refine(value=>/[A-Za-z]/.test(value)&&/[0-9]/.test(value),'비밀번호는 영문과 숫자를 함께 입력해 주세요.')}));if(!same((await password(v.currentPassword,user.password_salt)).hash,user.password_hash))return c.json({error:'현재 비밀번호가 올바르지 않습니다.'},401);const next=await password(v.password),ts=now();await c.env.DB.batch([c.env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?').bind(next.hash,next.salt,ts,user.id),c.env.DB.prepare('UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL').bind(ts,user.id)]);c.header('Set-Cookie','pva_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return c.json({ok:true})})
app.delete('/api/account',async c=>{const user=c.get('user');await input(c.req.raw,z.object({phrase:z.literal('탈퇴합니다')}));await c.env.DB.batch([
 c.env.DB.prepare('DELETE FROM task_status_events WHERE task_id IN (SELECT t.id FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE p.user_id=?)').bind(user.id),
 c.env.DB.prepare('DELETE FROM actions WHERE task_id IN (SELECT t.id FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE p.user_id=?)').bind(user.id),
 c.env.DB.prepare('DELETE FROM task_tags WHERE task_id IN (SELECT t.id FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE p.user_id=?) OR tag_id IN (SELECT id FROM tags WHERE user_id=?)').bind(user.id,user.id),
 c.env.DB.prepare('DELETE FROM reviews WHERE plan_id IN (SELECT id FROM plans WHERE user_id=?)').bind(user.id),
 c.env.DB.prepare('UPDATE reviews SET next_plan_id=NULL,updated_at=? WHERE next_plan_id IN (SELECT id FROM plans WHERE user_id=?)').bind(now(),user.id),
 c.env.DB.prepare('DELETE FROM plan_history WHERE plan_id IN (SELECT id FROM plans WHERE user_id=?)').bind(user.id),
 c.env.DB.prepare('DELETE FROM tasks WHERE plan_id IN (SELECT id FROM plans WHERE user_id=?)').bind(user.id),
 c.env.DB.prepare('DELETE FROM tags WHERE user_id=?').bind(user.id),
 c.env.DB.prepare('DELETE FROM plans WHERE user_id=?').bind(user.id),
 c.env.DB.prepare('DELETE FROM email_verifications WHERE user_id=?').bind(user.id),
 c.env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(user.id),
 c.env.DB.prepare('DELETE FROM users WHERE id=?').bind(user.id)
]);c.header('Set-Cookie','pva_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return c.json({ok:true})})
app.post('/api/auth/password-reset/request',async c=>{const v=await input(c.req.raw,emailSchema);if(!c.env.AUTH_SECRET)return c.json({error:'인증 설정이 없습니다.'},503);const user=await c.env.DB.prepare('SELECT id FROM users WHERE email=?').bind(v.email).first<{id:string}>();if(!user)return c.json({ok:true});const id=uid('reset'),raw=token(),value=code(),ts=now();await c.env.DB.prepare("UPDATE email_verifications SET status='expired',updated_at=? WHERE email=? AND status IN ('pending','verified')").bind(ts,v.email).run();await c.env.DB.prepare("INSERT INTO email_verifications(id,email,code_hash,flow_token_hash,status,expires_at,created_at,updated_at,purpose,user_id) VALUES(?,?,?,?,?,?,?,?, 'password_reset',?)").bind(id,v.email,await sign(value,c.env.AUTH_SECRET),await digest(raw),'pending',new Date(Date.now()+verificationTtlMinutes*60000).toISOString(),ts,ts,user.id).run();await sendVerificationEmail(c.env,v.email,value,'password_reset');return c.json({flowId:id,flowToken:raw})})
app.post('/api/auth/password-reset/verify',async c=>{const v=await input(c.req.raw,z.object({flowId:z.string(),flowToken:z.string(),code:z.string().regex(/^\d{6}$/,'인증번호 6자리를 입력해 주세요.')}));if(!c.env.AUTH_SECRET)return c.json({error:'인증 설정이 없습니다.'},503);const flow=await c.env.DB.prepare("SELECT id,code_hash FROM email_verifications WHERE id=? AND purpose='password_reset' AND flow_token_hash=? AND status='pending' AND expires_at>?").bind(v.flowId,await digest(v.flowToken),now()).first<{id:string;code_hash:string}>();if(!flow||!same(flow.code_hash,await sign(v.code,c.env.AUTH_SECRET)))return c.json({error:'인증번호가 올바르지 않거나 만료되었습니다.'},400);await c.env.DB.prepare("UPDATE email_verifications SET status='verified',updated_at=? WHERE id=?").bind(now(),flow.id).run();return c.json({ok:true})})
app.post('/api/auth/password-reset/complete',async c=>{const v=await input(c.req.raw,z.object({flowId:z.string(),flowToken:z.string(),password:z.string().min(8).max(128)}));const flow=await c.env.DB.prepare("SELECT user_id FROM email_verifications WHERE id=? AND purpose='password_reset' AND flow_token_hash=? AND status='verified' AND expires_at>?").bind(v.flowId,await digest(v.flowToken),now()).first<{user_id:string}>();if(!flow)return c.json({error:'재설정 인증이 만료되었거나 현재 창의 요청이 아닙니다.'},403);const hash=await password(v.password),ts=now();await c.env.DB.batch([c.env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?').bind(hash.hash,hash.salt,ts,flow.user_id),c.env.DB.prepare("UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL").bind(ts,flow.user_id),c.env.DB.prepare("UPDATE email_verifications SET status='completed',updated_at=? WHERE id=?").bind(ts,v.flowId)]);return c.json({ok:true})})

app.get('/api/plans',async c=>{const user=await sessionUser(c.req.raw,c.env.DB);if(!user)return c.json({error:'로그인이 필요합니다.'},401);return c.json((await c.env.DB.prepare(`SELECT p.*,(SELECT COUNT(*) FROM tasks t WHERE t.plan_id=p.id AND t.deleted_at IS NULL) task_count,(SELECT COUNT(*) FROM tasks t WHERE t.plan_id=p.id AND t.deleted_at IS NULL AND t.status='completed') completed_count,(SELECT COALESCE(SUM(t.estimated_minutes),0) FROM tasks t WHERE t.plan_id=p.id AND t.deleted_at IS NULL) task_estimated_minutes,(SELECT MAX(t.due_date) FROM tasks t WHERE t.plan_id=p.id AND t.deleted_at IS NULL) final_due_date FROM plans p WHERE p.user_id=? AND p.deleted_at IS NULL ORDER BY p.created_at DESC,p.id`).bind(user.id).all()).results)})
app.post('/api/plans',async c=>{const user=await sessionUser(c.req.raw,c.env.DB);if(!user)return c.json({error:'로그인이 필요합니다.'},401);const v=await input(c.req.raw,createPlanSchema),id=uid('plan'),ts=now();const ops:D1PreparedStatement[]=[c.env.DB.prepare(`INSERT INTO plans(id,user_id,title,priority,success_criteria,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).bind(id,user.id,v.title,v.priority,v.successCriteria,ts,ts)];for(const task of v.tasks){const taskId=uid('task');ops.push(c.env.DB.prepare('INSERT INTO tasks(id,plan_id,title,due_date,priority,estimated_minutes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(taskId,id,task.title,task.dueDate,task.priority,task.estimatedMinutes,ts,ts),...await tags(c.env.DB,taskId,task.tags,user.id))}await c.env.DB.batch(ops);return c.json({id,taskCount:v.tasks.length},201)})
app.put('/api/plans/:id',async c=>{const user=c.get('user');const v=await input(c.req.raw,planSchema),id=c.req.param('id'),ts=now();const old=await c.env.DB.prepare('SELECT * FROM plans WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(id,user.id).first<Record<string,unknown>>();if(!old)return c.json({error:'계획을 찾을 수 없습니다.'},404);const version=(await c.env.DB.prepare('SELECT COALESCE(MAX(h.version),0)+1 version FROM plan_history h JOIN plans p ON p.id=h.plan_id WHERE h.plan_id=? AND p.user_id=?').bind(id,user.id).first<number>('version'))??1;await c.env.DB.batch([c.env.DB.prepare('INSERT INTO plan_history(id,plan_id,version,title,priority,success_criteria,recorded_at) VALUES(?,?,?,?,?,?,?)').bind(uid('history'),id,version,old.title,old.priority,old.success_criteria,ts),c.env.DB.prepare('UPDATE plans SET title=?,priority=?,success_criteria=?,updated_at=? WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(v.title,v.priority,v.successCriteria,ts,id,user.id)]);return c.json({ok:true,historyVersion:version})})
app.delete('/api/plans/:id',async c=>{const user=await sessionUser(c.req.raw,c.env.DB);if(!user)return c.json({error:'로그인이 필요합니다.'},401);const ts=now(),r=await c.env.DB.prepare('UPDATE plans SET deleted_at=?,updated_at=? WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(ts,ts,c.req.param('id'),user.id).run();return r.meta.changes?c.json({ok:true}):c.json({error:'계획을 찾을 수 없습니다.'},404)})
app.get('/api/plans/:id/history',async c=>{const user=c.get('user'),id=c.req.param('id'),plan=await c.env.DB.prepare('SELECT id FROM plans WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(id,user.id).first();if(!plan)return c.json({error:'계획을 찾을 수 없습니다.'},404);return c.json((await c.env.DB.prepare('SELECT h.* FROM plan_history h WHERE h.plan_id=? ORDER BY h.version DESC').bind(id).all()).results)})

app.get('/api/tasks',async c=>{const user=c.get('user'),planId=c.req.query('planId');if(planId&&!await c.env.DB.prepare('SELECT id FROM plans WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(planId,user.id).first())return c.json({error:'계획을 찾을 수 없습니다.'},404);const values:unknown[]=[user.id],filters=['p.user_id=?','p.deleted_at IS NULL','t.deleted_at IS NULL'];const add=(sql:string,v?:string)=>{if(v){filters.push(sql);values.push(v)}};add('t.plan_id=?',planId);add('t.status=?',c.req.query('status'));add('t.priority=?',c.req.query('priority'));const q=c.req.query('q');if(q){filters.push('t.title LIKE ?');values.push(`%${q}%`)}const tag=c.req.query('tag');if(tag){filters.push('EXISTS(SELECT 1 FROM task_tags x JOIN tags y ON y.id=x.tag_id WHERE x.task_id=t.id AND y.user_id=? AND y.normalized_name=?)');values.push(user.id,tagParts(tag).normalizedName)}const orders:Record<string,string>={due:'t.due_date,t.created_at,t.id',priority:"CASE t.priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,t.due_date,t.id",created:'t.created_at DESC,t.id'};const rows=await c.env.DB.prepare(`${taskQuery(filters.join(' AND '))} ORDER BY ${orders[c.req.query('sort')??'due']??orders.due}`).bind(...values).all<Record<string,unknown>>();return c.json(rows.results.map(withTags))})
app.get('/api/tags',async c=>{const user=await sessionUser(c.req.raw,c.env.DB);if(!user)return c.json({error:'로그인이 필요합니다.'},401);return c.json((await c.env.DB.prepare(`SELECT g.id,g.name,g.normalized_name,g.search_key,COUNT(DISTINCT CASE WHEN t.deleted_at IS NULL THEN tt.task_id END) usage_count FROM tags g LEFT JOIN task_tags tt ON tt.tag_id=g.id LEFT JOIN tasks t ON t.id=tt.task_id WHERE g.user_id=? GROUP BY g.id,g.name,g.normalized_name,g.search_key ORDER BY usage_count DESC,g.name`).bind(user.id).all()).results)})
async function tags(db:D1Database,taskId:string,names:string[],userId:string){const ops:D1PreparedStatement[]=[];const unique=new Map<string,ReturnType<typeof tagParts>>();for(const raw of names){const part=tagParts(raw);if(part.name&&part.normalizedName&&!unique.has(part.normalizedName))unique.set(part.normalizedName,part)}for(const part of unique.values()){ops.push(db.prepare('INSERT OR IGNORE INTO tags(id,user_id,name,normalized_name,search_key) VALUES(?,?,?,?,?)').bind(uid('tag'),userId,part.name,part.normalizedName,part.searchKey));ops.push(db.prepare('INSERT OR IGNORE INTO task_tags(task_id,tag_id) SELECT ?,id FROM tags WHERE user_id=? AND normalized_name=?').bind(taskId,userId,part.normalizedName))}return ops}
app.post('/api/tasks',async c=>{const user=c.get('user'),v=await input(c.req.raw,taskSchema),plan=await planTaskCount(c.env.DB,v.planId,user.id);if(!plan)return c.json({error:'계획을 찾을 수 없습니다.'},404);if(Number(plan.task_count)>=MAX_TASKS_PER_PLAN)return c.json({error:`계획마다 할 일은 최대 ${MAX_TASKS_PER_PLAN}개까지 추가할 수 있습니다.`},409);const id=uid('task'),ts=now();await c.env.DB.batch([c.env.DB.prepare('INSERT INTO tasks(id,plan_id,title,due_date,priority,estimated_minutes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,v.planId,v.title,v.dueDate,v.priority,v.estimatedMinutes,ts,ts),...await tags(c.env.DB,id,v.tags,user.id)]);return c.json({id},201)})
app.put('/api/tasks/:id',async c=>{const user=c.get('user'),v=await input(c.req.raw,taskSchema),id=c.req.param('id'),ts=now();const old=await c.env.DB.prepare('SELECT t.plan_id FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.id=? AND p.user_id=? AND t.deleted_at IS NULL AND p.deleted_at IS NULL').bind(id,user.id).first<{plan_id:string}>();if(!old)return c.json({error:'할 일을 찾을 수 없습니다.'},404);const target=await planTaskCount(c.env.DB,v.planId,user.id);if(!target)return c.json({error:'이동할 계획을 찾을 수 없습니다.'},404);if(old.plan_id!==v.planId){const sourceCount=(await c.env.DB.prepare('SELECT COUNT(*) count FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.plan_id=? AND p.user_id=? AND t.deleted_at IS NULL').bind(old.plan_id,user.id).first<number>('count'))??0;if(sourceCount<=1)return c.json({error:'계획에는 할 일이 1개 이상 있어야 합니다.'},409);if(Number(target.task_count)>=MAX_TASKS_PER_PLAN)return c.json({error:`계획마다 할 일은 최대 ${MAX_TASKS_PER_PLAN}개까지 추가할 수 있습니다.`},409)}const result=await c.env.DB.batch([c.env.DB.prepare('UPDATE tasks SET plan_id=?,title=?,due_date=?,priority=?,estimated_minutes=?,updated_at=? WHERE id=? AND deleted_at IS NULL AND EXISTS(SELECT 1 FROM plans p WHERE p.id=tasks.plan_id AND p.user_id=?)').bind(v.planId,v.title,v.dueDate,v.priority,v.estimatedMinutes,ts,id,user.id),c.env.DB.prepare('DELETE FROM task_tags WHERE task_id=? AND EXISTS(SELECT 1 FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.id=task_tags.task_id AND p.user_id=?)').bind(id,user.id),...await tags(c.env.DB,id,v.tags,user.id)]);return result[0].meta.changes?c.json({ok:true}):c.json({error:'할 일을 찾을 수 없습니다.'},404)})
app.delete('/api/tasks/:id',async c=>{const user=c.get('user'),id=c.req.param('id'),task=await c.env.DB.prepare('SELECT t.plan_id FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.id=? AND p.user_id=? AND t.deleted_at IS NULL AND p.deleted_at IS NULL').bind(id,user.id).first<{plan_id:string}>();if(!task)return c.json({error:'할 일을 찾을 수 없습니다.'},404);const count=(await c.env.DB.prepare('SELECT COUNT(*) count FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.plan_id=? AND p.user_id=? AND t.deleted_at IS NULL').bind(task.plan_id,user.id).first<number>('count'))??0;if(count<=1)return c.json({error:'계획에는 할 일이 1개 이상 있어야 합니다.'},409);const ts=now(),r=await c.env.DB.prepare('UPDATE tasks SET deleted_at=?,updated_at=? WHERE id=? AND deleted_at IS NULL AND EXISTS(SELECT 1 FROM plans p WHERE p.id=tasks.plan_id AND p.user_id=?)').bind(ts,ts,id,user.id).run();return r.meta.changes?c.json({ok:true}):c.json({error:'할 일을 찾을 수 없습니다.'},404)})
app.post('/api/tasks/:id/status',async c=>{const user=c.get('user'),v=await input(c.req.raw,statusSchema),id=c.req.param('id'),ts=now(),to=v.completed?'completed':'active',from=v.completed?'active':'completed';const taskExists=await c.env.DB.prepare('SELECT t.id FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.id=? AND p.user_id=? AND t.deleted_at IS NULL AND p.deleted_at IS NULL').bind(id,user.id).first();if(!taskExists)return c.json({error:'할 일을 찾을 수 없습니다.'},404);if(v.completed){const action=await c.env.DB.prepare('SELECT a.id FROM actions a JOIN tasks t ON t.id=a.task_id JOIN plans p ON p.id=t.plan_id WHERE a.task_id=? AND p.user_id=? LIMIT 1').bind(id,user.id).first();if(!action)return c.json({error:'완료하려면 작업 기록을 먼저 남겨 주세요.'},409)}const r=await c.env.DB.batch([c.env.DB.prepare(`INSERT OR IGNORE INTO task_status_events(id,task_id,idempotency_key,from_status,to_status,version_before,created_at) SELECT ?,?,?,?,?,?,? FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.id=? AND p.user_id=? AND t.status=? AND t.status_version=? AND t.deleted_at IS NULL`).bind(uid('event'),id,v.idempotencyKey,from,to,v.expectedVersion,ts,id,user.id,from,v.expectedVersion),c.env.DB.prepare('UPDATE tasks SET status=?,status_version=status_version+1,completed_at=?,updated_at=? WHERE id=? AND status=? AND status_version=? AND deleted_at IS NULL AND EXISTS(SELECT 1 FROM plans p WHERE p.id=tasks.plan_id AND p.user_id=?)').bind(to,v.completed?ts:null,ts,id,from,v.expectedVersion,user.id)]);const task=await c.env.DB.prepare('SELECT t.* FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.id=? AND p.user_id=? AND t.deleted_at IS NULL').bind(id,user.id).first();return c.json({changed:Boolean(r[1].meta.changes),task})})

app.get('/api/actions',async c=>{const user=c.get('user'),planId=c.req.query('planId'),values:unknown[]=[user.id];if(planId&&!await c.env.DB.prepare('SELECT id FROM plans WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(planId,user.id).first())return c.json({error:'계획을 찾을 수 없습니다.'},404);let extra='';if(planId){extra=' AND t.plan_id=?';values.push(planId)}return c.json((await c.env.DB.prepare(`SELECT a.*,t.title task_title,t.plan_id FROM actions a JOIN tasks t ON t.id=a.task_id JOIN plans p ON p.id=t.plan_id WHERE p.user_id=? AND p.deleted_at IS NULL AND t.deleted_at IS NULL${extra} ORDER BY a.worked_on DESC,a.created_at DESC,a.id`).bind(...values).all()).results)})
app.post('/api/actions',async c=>{const user=c.get('user'),v=await input(c.req.raw,actionSchema),task=await c.env.DB.prepare('SELECT t.status FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.id=? AND p.user_id=? AND t.deleted_at IS NULL AND p.deleted_at IS NULL').bind(v.taskId,user.id).first<{status:string}>();if(!task)return c.json({error:'할 일을 찾을 수 없습니다.'},404);if(task.status==='completed')return c.json({error:'완료된 할 일에는 작업 기록을 추가할 수 없습니다. 완료 취소 후 다시 시도해 주세요.'},409);const id=uid('action');await c.env.DB.prepare('INSERT INTO actions(id,task_id,worked_on,actual_minutes,note,created_at) VALUES(?,?,?,?,?,?)').bind(id,v.taskId,v.workedOn,v.actualMinutes,v.note,now()).run();return c.json({id},201)})

app.get('/api/reviews',async c=>{const user=c.get('user');return c.json((await c.env.DB.prepare('SELECT r.*,p.title plan_title,np.title next_plan_title FROM reviews r JOIN plans p ON p.id=r.plan_id LEFT JOIN plans np ON np.id=r.next_plan_id AND np.user_id=p.user_id WHERE p.user_id=? AND p.deleted_at IS NULL ORDER BY r.created_at DESC').bind(user.id).all()).results)})
app.post('/api/reviews',async c=>{const user=c.get('user'),v=await input(c.req.raw,reviewSchema),id=uid('review'),ts=now();const r=await c.env.DB.prepare('INSERT INTO reviews(id,plan_id,improvement_text,created_at,updated_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM plans WHERE id=? AND user_id=? AND deleted_at IS NULL)').bind(id,v.planId,v.improvementText,ts,ts,v.planId,user.id).run();return r.meta.changes?c.json({id},201):c.json({error:'계획을 찾을 수 없습니다.'},404)})

function seoulToday(){return seoulDate(new Date())}
app.get('/api/summary',async c=>{const user=c.get('user'),planId=c.req.query('planId');if(!planId)return c.json({error:'planId가 필요합니다.'},400);const plan=await c.env.DB.prepare('SELECT id FROM plans WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(planId,user.id).first();if(!plan)return c.json({error:'계획을 찾을 수 없습니다.'},404);const row=await c.env.DB.prepare(`SELECT COUNT(*) planned_count,SUM(CASE WHEN t.status='completed' THEN 1 ELSE 0 END) completed_count,SUM(CASE WHEN t.status='active' AND t.due_date<? THEN 1 ELSE 0 END) overdue_count,COALESCE(SUM(t.estimated_minutes),0) estimated_minutes,COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM actions x WHERE x.task_id=t.id) THEN t.estimated_minutes ELSE 0 END),0) tracked_estimated_minutes,SUM(CASE WHEN EXISTS(SELECT 1 FROM actions x WHERE x.task_id=t.id) THEN 1 ELSE 0 END) tracked_count,COALESCE(SUM((SELECT COALESCE(SUM(a.actual_minutes),0) FROM actions a WHERE a.task_id=t.id)),0) actual_minutes FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.plan_id=? AND p.user_id=? AND p.deleted_at IS NULL AND t.deleted_at IS NULL`).bind(seoulToday(),planId,user.id).first<Record<string,number>>();return c.json({...row,difference_minutes:Number(row?.actual_minutes??0)-Number(row?.tracked_estimated_minutes??0),today_seoul:seoulToday()})})
app.get('/api/evidence/:metric',async c=>{const user=c.get('user'),metric=c.req.param('metric'),planId=c.req.query('planId');if(!planId)return c.json({error:'planId가 필요합니다.'},400);const clauses:Record<string,string>={planned:'1=1',completed:"t.status='completed'",overdue:"t.status='active' AND t.due_date<?",tracked:'EXISTS(SELECT 1 FROM actions a WHERE a.task_id=t.id)',estimated:'1=1',actual:'EXISTS(SELECT 1 FROM actions a WHERE a.task_id=t.id)'};if(!clauses[metric])return c.json({error:'지원하지 않는 집계입니다.'},400);const plan=await c.env.DB.prepare('SELECT id FROM plans WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(planId,user.id).first();if(!plan)return c.json({error:'계획을 찾을 수 없습니다.'},404);const values:unknown[]=[user.id,planId];if(metric==='overdue')values.push(seoulToday());const rows=await c.env.DB.prepare(`${taskQuery(`p.user_id=? AND p.deleted_at IS NULL AND t.plan_id=? AND t.deleted_at IS NULL AND ${clauses[metric]}`)} ORDER BY t.due_date,t.id`).bind(...values).all<Record<string,unknown>>();return c.json(rows.results.map(withTags))})
app.get('/api/export',async c=>{const user=c.get('user'),data:Record<string,unknown>={exportedAt:now(),contract:'pds-schema-v3',timezone:'Asia/Seoul',account:{id:user.id,name:user.name,email:user.email}};const queries:Record<string,string>={plans:'SELECT * FROM plans WHERE user_id=?',plan_history:'SELECT h.* FROM plan_history h JOIN plans p ON p.id=h.plan_id WHERE p.user_id=?',tasks:'SELECT t.* FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE p.user_id=?',tags:'SELECT * FROM tags WHERE user_id=?',task_tags:'SELECT tt.* FROM task_tags tt JOIN tasks t ON t.id=tt.task_id JOIN plans p ON p.id=t.plan_id JOIN tags g ON g.id=tt.tag_id WHERE p.user_id=? AND g.user_id=p.user_id',actions:'SELECT a.* FROM actions a JOIN tasks t ON t.id=a.task_id JOIN plans p ON p.id=t.plan_id WHERE p.user_id=?',task_status_events:'SELECT e.* FROM task_status_events e JOIN tasks t ON t.id=e.task_id JOIN plans p ON p.id=t.plan_id WHERE p.user_id=?',reviews:'SELECT r.* FROM reviews r JOIN plans p ON p.id=r.plan_id WHERE p.user_id=?'};for(const [name,sql] of Object.entries(queries))data[name]=(await c.env.DB.prepare(sql).bind(user.id).all()).results;c.header('Content-Disposition',`attachment; filename="plan-vs-action-${now().slice(0,10)}.json"`);c.header('Content-Type','application/json; charset=UTF-8');return c.body(JSON.stringify(data,null,2))})

export default app
