import { Hono } from 'hono'
import { z } from 'zod'

type Bindings = { DB: D1Database }
const app = new Hono<{ Bindings: Bindings }>()
const WORKSPACE = 'public'
const MAX_TASKS_PER_PLAN = 20
const priority = z.enum(['low', 'medium', 'high'])
const calendarDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/)
const planFields = { title:z.string().trim().min(1).max(120), priority, successCriteria:z.string().trim().min(1).max(1000) }
const taskFields = { title:z.string().trim().min(1).max(200), dueDate:calendarDate, priority, estimatedMinutes:z.number().int().min(0), tags:z.array(z.string().trim().min(1).max(30)).max(10).default([]) }
const planSchema = z.object(planFields)
const createPlanSchema = z.object({...planFields,tasks:z.array(z.object(taskFields)).min(1,'할 일을 1개 이상 추가해 주세요.').max(MAX_TASKS_PER_PLAN,`할 일은 최대 ${MAX_TASKS_PER_PLAN}개까지 추가할 수 있습니다.`)})
const taskSchema = z.object({ planId:z.string(), ...taskFields })
const actionSchema = z.object({ taskId:z.string(), startedAt:z.string().datetime({offset:true}), endedAt:z.string().datetime({offset:true}), actualMinutes:z.number().int().min(0), note:z.string().trim().max(1000).default('') }).refine(v=>v.startedAt<=v.endedAt,{message:'종료 시각을 확인해 주세요.'})
const statusSchema = z.object({ completed:z.boolean(), expectedVersion:z.number().int().min(0), idempotencyKey:z.string().min(8).max(200) })
const reviewSchema = z.object({ planId:z.string(), improvementText:z.string().trim().min(1).max(500) })
const now=()=>new Date().toISOString()
const uid=(prefix:string)=>`${prefix}_${crypto.randomUUID()}`

async function input<T>(request:Request,schema:z.ZodType<T>){ return schema.parse(await request.json()) }
function taskQuery(where:string){return `SELECT t.*,p.title plan_title,COALESCE(GROUP_CONCAT(DISTINCT g.name),'') tag_names,COALESCE((SELECT SUM(a.actual_minutes) FROM actions a WHERE a.task_id=t.id),0) actual_minutes FROM tasks t JOIN plans p ON p.id=t.plan_id LEFT JOIN task_tags tt ON tt.task_id=t.id LEFT JOIN tags g ON g.id=tt.tag_id WHERE ${where} GROUP BY t.id`}
function withTags(row:Record<string,unknown>){return {...row,tags:typeof row.tag_names==='string'&&row.tag_names?row.tag_names.split(','):[]}}
async function planTaskCount(db:D1Database,planId:string){return db.prepare('SELECT p.id,COUNT(t.id) task_count FROM plans p LEFT JOIN tasks t ON t.plan_id=p.id AND t.deleted_at IS NULL WHERE p.id=? AND p.workspace_id=? AND p.deleted_at IS NULL GROUP BY p.id').bind(planId,WORKSPACE).first<{id:string;task_count:number}>()}
function tagParts(value:string){
 let name=value.normalize('NFKC').trim().replace(/\s+/g,' ').replace(/^#+\s*/,'')
 const wrappers:Record<string,string>={'[':']','(':')','{':'}','"':'"',"'":"'"}
 const closing=wrappers[name[0]]
 if(closing&&name.endsWith(closing))name=name.slice(1,-1).trim()
 const normalizedName=name.toLocaleLowerCase('ko-KR').replace(/\s+/g,'')
 const ignored=`._-[](){}"'`
 const searchKey=[...normalizedName].filter(character=>!ignored.includes(character)).join('')
 return{name,normalizedName,searchKey}
}

app.use('/api/*',async(c,next)=>{await next();c.header('Cache-Control','no-store');c.header('X-Content-Type-Options','nosniff')})
app.onError((error,c)=>error instanceof z.ZodError?c.json({error:error.issues[0]?.message??'입력값을 확인해 주세요.',details:error.issues},400):(console.error(error),c.json({error:'요청을 처리하지 못했습니다.'},500)))
app.get('/api/health',c=>c.json({ok:true,database:'D1',timezone:'Asia/Seoul'}))

app.get('/api/plans',async c=>c.json((await c.env.DB.prepare(`SELECT p.*,(SELECT COUNT(*) FROM tasks t WHERE t.plan_id=p.id AND t.deleted_at IS NULL) task_count,(SELECT COUNT(*) FROM tasks t WHERE t.plan_id=p.id AND t.deleted_at IS NULL AND t.status='completed') completed_count,(SELECT COALESCE(SUM(t.estimated_minutes),0) FROM tasks t WHERE t.plan_id=p.id AND t.deleted_at IS NULL) task_estimated_minutes FROM plans p WHERE p.workspace_id=? AND p.deleted_at IS NULL ORDER BY p.created_at DESC,p.id`).bind(WORKSPACE).all()).results))
app.post('/api/plans',async c=>{const v=await input(c.req.raw,createPlanSchema),id=uid('plan'),ts=now();const ops:D1PreparedStatement[]=[c.env.DB.prepare(`INSERT INTO plans(id,workspace_id,title,priority,success_criteria,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).bind(id,WORKSPACE,v.title,v.priority,v.successCriteria,ts,ts)];for(const task of v.tasks){const taskId=uid('task');ops.push(c.env.DB.prepare('INSERT INTO tasks(id,plan_id,title,due_date,priority,estimated_minutes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(taskId,id,task.title,task.dueDate,task.priority,task.estimatedMinutes,ts,ts),...await tags(c.env.DB,taskId,task.tags))}await c.env.DB.batch(ops);return c.json({id,taskCount:v.tasks.length},201)})
app.put('/api/plans/:id',async c=>{const v=await input(c.req.raw,planSchema),id=c.req.param('id'),ts=now();const old=await c.env.DB.prepare('SELECT * FROM plans WHERE id=? AND workspace_id=? AND deleted_at IS NULL').bind(id,WORKSPACE).first<Record<string,unknown>>();if(!old)return c.json({error:'계획을 찾을 수 없습니다.'},404);const version=(await c.env.DB.prepare('SELECT COALESCE(MAX(version),0)+1 version FROM plan_history WHERE plan_id=?').bind(id).first<number>('version'))??1;await c.env.DB.batch([c.env.DB.prepare('INSERT INTO plan_history(id,plan_id,version,title,priority,success_criteria,recorded_at) VALUES(?,?,?,?,?,?,?)').bind(uid('history'),id,version,old.title,old.priority,old.success_criteria,ts),c.env.DB.prepare('UPDATE plans SET title=?,priority=?,success_criteria=?,updated_at=? WHERE id=?').bind(v.title,v.priority,v.successCriteria,ts,id)]);return c.json({ok:true,historyVersion:version})})
app.delete('/api/plans/:id',async c=>{const ts=now(),r=await c.env.DB.prepare('UPDATE plans SET deleted_at=?,updated_at=? WHERE id=? AND workspace_id=? AND deleted_at IS NULL').bind(ts,ts,c.req.param('id'),WORKSPACE).run();return r.meta.changes?c.json({ok:true}):c.json({error:'계획을 찾을 수 없습니다.'},404)})
app.get('/api/plans/:id/history',async c=>c.json((await c.env.DB.prepare('SELECT * FROM plan_history WHERE plan_id=? ORDER BY version DESC').bind(c.req.param('id')).all()).results))

app.get('/api/tasks',async c=>{const values:unknown[]=[WORKSPACE],filters=['p.workspace_id=?','p.deleted_at IS NULL','t.deleted_at IS NULL'];const add=(sql:string,v?:string)=>{if(v){filters.push(sql);values.push(v)}};add('t.plan_id=?',c.req.query('planId'));add('t.status=?',c.req.query('status'));add('t.priority=?',c.req.query('priority'));const q=c.req.query('q');if(q){filters.push('t.title LIKE ?');values.push(`%${q}%`)}const tag=c.req.query('tag');if(tag){filters.push('EXISTS(SELECT 1 FROM task_tags x JOIN tags y ON y.id=x.tag_id WHERE x.task_id=t.id AND y.normalized_name=?)');values.push(tagParts(tag).normalizedName)}const orders:Record<string,string>={due:'t.due_date,t.created_at,t.id',priority:"CASE t.priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,t.due_date,t.id",created:'t.created_at DESC,t.id'};const rows=await c.env.DB.prepare(`${taskQuery(filters.join(' AND '))} ORDER BY ${orders[c.req.query('sort')??'due']??orders.due}`).bind(...values).all<Record<string,unknown>>();return c.json(rows.results.map(withTags))})
app.get('/api/tags',async c=>c.json((await c.env.DB.prepare(`SELECT g.id,g.name,g.normalized_name,g.search_key,COUNT(DISTINCT CASE WHEN t.deleted_at IS NULL THEN tt.task_id END) usage_count FROM tags g LEFT JOIN task_tags tt ON tt.tag_id=g.id LEFT JOIN tasks t ON t.id=tt.task_id WHERE g.workspace_id=? GROUP BY g.id,g.name,g.normalized_name,g.search_key ORDER BY usage_count DESC,g.name`).bind(WORKSPACE).all()).results))
async function tags(db:D1Database,taskId:string,names:string[]){const ops:D1PreparedStatement[]=[];const unique=new Map<string,ReturnType<typeof tagParts>>();for(const raw of names){const part=tagParts(raw);if(part.name&&part.normalizedName&&!unique.has(part.normalizedName))unique.set(part.normalizedName,part)}for(const part of unique.values()){ops.push(db.prepare('INSERT OR IGNORE INTO tags(id,workspace_id,name,normalized_name,search_key) VALUES(?,?,?,?,?)').bind(uid('tag'),WORKSPACE,part.name,part.normalizedName,part.searchKey));ops.push(db.prepare('INSERT OR IGNORE INTO task_tags(task_id,tag_id) SELECT ?,id FROM tags WHERE workspace_id=? AND normalized_name=?').bind(taskId,WORKSPACE,part.normalizedName))}return ops}
app.post('/api/tasks',async c=>{const v=await input(c.req.raw,taskSchema),plan=await planTaskCount(c.env.DB,v.planId);if(!plan)return c.json({error:'계획을 찾을 수 없습니다.'},404);if(Number(plan.task_count)>=MAX_TASKS_PER_PLAN)return c.json({error:`계획마다 할 일은 최대 ${MAX_TASKS_PER_PLAN}개까지 추가할 수 있습니다.`},409);const id=uid('task'),ts=now();await c.env.DB.batch([c.env.DB.prepare('INSERT INTO tasks(id,plan_id,title,due_date,priority,estimated_minutes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,v.planId,v.title,v.dueDate,v.priority,v.estimatedMinutes,ts,ts),...await tags(c.env.DB,id,v.tags)]);return c.json({id},201)})
app.put('/api/tasks/:id',async c=>{const v=await input(c.req.raw,taskSchema),id=c.req.param('id'),ts=now();const old=await c.env.DB.prepare('SELECT plan_id FROM tasks WHERE id=? AND deleted_at IS NULL').bind(id).first<{plan_id:string}>();if(!old)return c.json({error:'할 일을 찾을 수 없습니다.'},404);if(old.plan_id!==v.planId){const sourceCount=(await c.env.DB.prepare('SELECT COUNT(*) count FROM tasks WHERE plan_id=? AND deleted_at IS NULL').bind(old.plan_id).first<number>('count'))??0;if(sourceCount<=1)return c.json({error:'계획에는 할 일이 1개 이상 있어야 합니다.'},409);const target=await planTaskCount(c.env.DB,v.planId);if(!target)return c.json({error:'이동할 계획을 찾을 수 없습니다.'},404);if(Number(target.task_count)>=MAX_TASKS_PER_PLAN)return c.json({error:`계획마다 할 일은 최대 ${MAX_TASKS_PER_PLAN}개까지 추가할 수 있습니다.`},409)}const result=await c.env.DB.batch([c.env.DB.prepare('UPDATE tasks SET plan_id=?,title=?,due_date=?,priority=?,estimated_minutes=?,updated_at=? WHERE id=? AND deleted_at IS NULL').bind(v.planId,v.title,v.dueDate,v.priority,v.estimatedMinutes,ts,id),c.env.DB.prepare('DELETE FROM task_tags WHERE task_id=?').bind(id),...await tags(c.env.DB,id,v.tags)]);return result[0].meta.changes?c.json({ok:true}):c.json({error:'할 일을 찾을 수 없습니다.'},404)})
app.delete('/api/tasks/:id',async c=>{const id=c.req.param('id'),task=await c.env.DB.prepare('SELECT plan_id FROM tasks WHERE id=? AND deleted_at IS NULL').bind(id).first<{plan_id:string}>();if(!task)return c.json({error:'할 일을 찾을 수 없습니다.'},404);const count=(await c.env.DB.prepare('SELECT COUNT(*) count FROM tasks WHERE plan_id=? AND deleted_at IS NULL').bind(task.plan_id).first<number>('count'))??0;if(count<=1)return c.json({error:'계획에는 할 일이 1개 이상 있어야 합니다.'},409);const ts=now(),r=await c.env.DB.prepare('UPDATE tasks SET deleted_at=?,updated_at=? WHERE id=? AND deleted_at IS NULL').bind(ts,ts,id).run();return r.meta.changes?c.json({ok:true}):c.json({error:'할 일을 찾을 수 없습니다.'},404)})
app.post('/api/tasks/:id/status',async c=>{const v=await input(c.req.raw,statusSchema),id=c.req.param('id'),ts=now(),to=v.completed?'completed':'active',from=v.completed?'active':'completed';const r=await c.env.DB.batch([c.env.DB.prepare(`INSERT OR IGNORE INTO task_status_events(id,task_id,idempotency_key,from_status,to_status,version_before,created_at) SELECT ?,?,?,?,?,?,? FROM tasks WHERE id=? AND status=? AND status_version=? AND deleted_at IS NULL`).bind(uid('event'),id,v.idempotencyKey,from,to,v.expectedVersion,ts,id,from,v.expectedVersion),c.env.DB.prepare('UPDATE tasks SET status=?,status_version=status_version+1,completed_at=?,updated_at=? WHERE id=? AND status=? AND status_version=? AND deleted_at IS NULL').bind(to,v.completed?ts:null,ts,id,from,v.expectedVersion)]);const task=await c.env.DB.prepare('SELECT * FROM tasks WHERE id=? AND deleted_at IS NULL').bind(id).first();return task?c.json({changed:Boolean(r[1].meta.changes),task}):c.json({error:'할 일을 찾을 수 없습니다.'},404)})

app.get('/api/actions',async c=>{const planId=c.req.query('planId'),values:unknown[]=[WORKSPACE];let extra='';if(planId){extra=' AND t.plan_id=?';values.push(planId)}return c.json((await c.env.DB.prepare(`SELECT a.*,t.title task_title,t.plan_id FROM actions a JOIN tasks t ON t.id=a.task_id JOIN plans p ON p.id=t.plan_id WHERE p.workspace_id=? AND t.deleted_at IS NULL${extra} ORDER BY a.started_at DESC,a.id`).bind(...values).all()).results)})
app.post('/api/actions',async c=>{const v=await input(c.req.raw,actionSchema),task=await c.env.DB.prepare('SELECT t.status FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.id=? AND p.workspace_id=? AND t.deleted_at IS NULL AND p.deleted_at IS NULL').bind(v.taskId,WORKSPACE).first<{status:string}>();if(!task)return c.json({error:'할 일을 찾을 수 없습니다.'},404);if(task.status==='completed')return c.json({error:'완료된 할 일에는 작업 기록을 추가할 수 없습니다. 완료 취소 후 다시 시도해 주세요.'},409);const id=uid('action');await c.env.DB.prepare('INSERT INTO actions(id,task_id,started_at,ended_at,actual_minutes,note,created_at) VALUES(?,?,?,?,?,?,?)').bind(id,v.taskId,v.startedAt,v.endedAt,v.actualMinutes,v.note,now()).run();return c.json({id},201)})

app.get('/api/reviews',async c=>c.json((await c.env.DB.prepare('SELECT r.*,p.title plan_title,np.title next_plan_title FROM reviews r JOIN plans p ON p.id=r.plan_id LEFT JOIN plans np ON np.id=r.next_plan_id WHERE r.workspace_id=? ORDER BY r.created_at DESC').bind(WORKSPACE).all()).results))
app.post('/api/reviews',async c=>{const v=await input(c.req.raw,reviewSchema),id=uid('review'),ts=now();const r=await c.env.DB.prepare('INSERT INTO reviews(id,workspace_id,plan_id,improvement_text,created_at,updated_at) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM plans WHERE id=? AND workspace_id=? AND deleted_at IS NULL)').bind(id,WORKSPACE,v.planId,v.improvementText,ts,ts,v.planId,WORKSPACE).run();return r.meta.changes?c.json({id},201):c.json({error:'계획을 찾을 수 없습니다.'},404)})

function seoulToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
app.get('/api/summary',async c=>{const planId=c.req.query('planId');if(!planId)return c.json({error:'planId가 필요합니다.'},400);const row=await c.env.DB.prepare(`SELECT COUNT(*) planned_count,SUM(CASE WHEN t.status='completed' THEN 1 ELSE 0 END) completed_count,SUM(CASE WHEN t.status='active' AND t.due_date<? THEN 1 ELSE 0 END) overdue_count,COALESCE(SUM(t.estimated_minutes),0) estimated_minutes,COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM actions x WHERE x.task_id=t.id) THEN t.estimated_minutes ELSE 0 END),0) tracked_estimated_minutes,SUM(CASE WHEN EXISTS(SELECT 1 FROM actions x WHERE x.task_id=t.id) THEN 1 ELSE 0 END) tracked_count,COALESCE(SUM((SELECT COALESCE(SUM(a.actual_minutes),0) FROM actions a WHERE a.task_id=t.id)),0) actual_minutes FROM tasks t JOIN plans p ON p.id=t.plan_id WHERE t.plan_id=? AND p.workspace_id=? AND t.deleted_at IS NULL`).bind(seoulToday(),planId,WORKSPACE).first<Record<string,number>>();return c.json({...row,difference_minutes:Number(row?.actual_minutes??0)-Number(row?.tracked_estimated_minutes??0),today_seoul:seoulToday()})})
app.get('/api/evidence/:metric',async c=>{const metric=c.req.param('metric'),planId=c.req.query('planId');if(!planId)return c.json({error:'planId가 필요합니다.'},400);const clauses:Record<string,string>={planned:'1=1',completed:"t.status='completed'",overdue:"t.status='active' AND t.due_date<?",tracked:'EXISTS(SELECT 1 FROM actions a WHERE a.task_id=t.id)',estimated:'1=1',actual:'EXISTS(SELECT 1 FROM actions a WHERE a.task_id=t.id)'};if(!clauses[metric])return c.json({error:'지원하지 않는 집계입니다.'},400);const values:unknown[]=[WORKSPACE,planId];if(metric==='overdue')values.push(seoulToday());const rows=await c.env.DB.prepare(`${taskQuery(`p.workspace_id=? AND t.plan_id=? AND t.deleted_at IS NULL AND ${clauses[metric]}`)} ORDER BY t.due_date,t.id`).bind(...values).all<Record<string,unknown>>();return c.json(rows.results.map(withTags))})
app.get('/api/export',async c=>{const names=['workspaces','plans','plan_history','tasks','tags','task_tags','actions','task_status_events','reviews'];const data:Record<string,unknown>={exportedAt:now(),contract:'pds-schema-v2',timezone:'Asia/Seoul'};for(const name of names)data[name]=(await c.env.DB.prepare(`SELECT * FROM ${name}`).all()).results;c.header('Content-Disposition',`attachment; filename="plan-vs-action-${now().slice(0,10)}.json"`);return c.json(data)})

export default app
